version: "3"

services: 
  node:
    image: "nodeapi"
    restart: unless-stopped
    working_dir: /home/node/api
    container_name: api
    environment:
      - PORT=3000
      - MONGO_DB=node1
      - NODE_ENV=production
      - MONGO_PORT=27017
      - MONGO_HOSTNAME=mongodb
      - JWT_SECRET=xasdD3d309NsdLsadNMDds
    volumes:
      - ./api:/home/node/api
    ports:
      - "3000:3000"
    command: "npm i && npm start"
    networks:
      - api-net 

  mongo:
    image: mongo
    container_name: mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    networks:
      - api-net 
    volumes:  
      - ./data:/data/db 
 
networks:
  api-net:
    driver: bridge